name: gh-pages
on: push

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
        
      - name: Install dependencies
        run: |
          pip install mkdocs==0.17.2
          pip install mkdocs-material==2.5.2
          pip install python-markdown-math
          pip install pymdown-extensions
          pip install git+https://github.com/szcf-weiya/mkdocs-git-revision-date-plugin.git
      
      - name: Build
        run: |
          python gentag.py
          mkdocs build
          mv rmds/_site/ site/rmds
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site